### ISSUE TITLE
store task info

### ISSUE THREAD

**Issue by PP-YE** [adform/sprint#12]
where to store the task info

**Comment by sauliusvl** [comment]
Hi, could you clarify a bit, what do you mean by "task info" exactly? and where do you want to store it?

**Comment by PP-YE** [comment]
> Hi, could you clarify a bit, what do you mean by "task info" exactly? and where do you want to store it?



> Hi, could you clarify a bit, what do you mean by "task info" exactly? and where do you want to store it?

when we run one-off tasks on mesos cluster, the task have some info, like cpu,mem,command, I want to store them, in database

**Comment by sauliusvl** [comment]
Sprint itself stores the state in Zookeeper (https://github.com/adform/sprint/blob/master/src/main/scala/com/adform/sprint/state/ContainerRunStore.scala#L59) under `/runs/<uuid>`, the value being the task description JSON, same thing as returned by the API when GET'ing `/v1/runs/<uuid>`, so you can query zookeper or the API to get this information.

Currently there's no support for switching to a different storage, but I guess it wouldn't be too hard to implement a custom `ContainerRunStore` (https://github.com/adform/sprint/blob/master/src/main/scala/com/adform/sprint/state/ContainerRunStore.scala#L26).

**Comment by PP-YE** [comment]
> Sprint itself stores the state in Zookeeper (https://github.com/adform/sprint/blob/master/src/main/scala/com/adform/sprint/state/ContainerRunStore.scala#L59) under `/runs/<uuid>`, the value being the task description JSON, same thing as returned by the API when GET'ing `/v1/runs/<uuid>`, so you can query zookeper or the API to get this information.
> 
> Currently there's no support for switching to a different storage, but I guess it wouldn't be too hard to implement a custom `ContainerRunStore` (https://github.com/adform/sprint/blob/master/src/main/scala/com/adform/sprint/state/ContainerRunStore.scala#L26).

Thanks very much!
